use_frameworks!

source 'https://github.com/QiuYeHong90/YYImage.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end


target 'JNLiveSDK_Example' do
  pod 'JNLiveSDK', :path => '../'

  target 'JNLiveSDK_Tests' do
    inherit! :search_paths

    
  end
end
